import "jquery";
import "./vendor/jquery.waypoints.min";
import "owl.carousel";
import "jquery-scrollify";
import "./vendor/jquery.counterup.min";
import navigationHandler from "./utils/Navigation";
import counter from "./utils/Counter";
//import scrollify from './utils/Scrollify';
import testimonialCarousel from "./utils/TestimonialCarousel";
import popup from "./utils/Popup";
import cookies from "./utils/Cookies";
import smallText from "./utils/SmallText";
import inputFile from "./utils/InputFile";
import formilla from "./utils/formilla";
import register from "./controller/auth/register";
import logout from "./controller/auth/logout";
import newPost from "./controller/newPost";
import deletePost from "./controller/deletePost";
import me from "./utils/me";
import blogComments from "./view/blogComments";
import passwordRecover from "./controller/auth/passwordRecover";

//import aws_s3 from './utils/aws_s3';

navigationHandler();
counter();
//scrollify();
testimonialCarousel();
popup();
cookies();
smallText();
inputFile();
formilla();
//aws_s3();
register();
newPost();
deletePost();
me();
logout();
blogComments();
passwordRecover();
